platform :ios, '17.0'

target 'iosApp' do
   pod 'composeApp', :path => '../composeApp' # Needed for resources to work on iOS, otherwise it won't generate the files if the project uses cocoapods in composeApp/build/compose/ios/composeApp/compose-resources
   pod 'GoogleMaps'
end
